baseURL = "http://judy-cold.github.io/"
languageCode = "en-us"
title = "Judy Cold"
theme = "sam"

[[params.mainMenu]]
    link = "/"
    text = "Hello"

[[params.mainMenu]]
    link = "/gallery"
    text = "I'm Judy ðŸŒ¿"
